# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MAIN_WINDOWjlElCa.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QGridLayout, QGroupBox, QHBoxLayout, QHeaderView,
    QLCDNumber, QLabel, QLineEdit, QMainWindow,
    QMenu, QMenuBar, QProgressBar, QPushButton,
    QSizePolicy, QSlider, QStackedWidget, QStatusBar,
    QTableWidget, QTableWidgetItem, QTextEdit, QVBoxLayout,
    QWidget)
import resource_rc
import resource_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1310, 700)
        self.actionTutorial_Tab = QAction(MainWindow)
        self.actionTutorial_Tab.setObjectName(u"actionTutorial_Tab")
        self.actionAbout_Us = QAction(MainWindow)
        self.actionAbout_Us.setObjectName(u"actionAbout_Us")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(0, 10, 141, 631))
        self.frame.setFrameShape(QFrame.Shape.WinPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.ProjectName = QLabel(self.frame)
        self.ProjectName.setObjectName(u"ProjectName")
        self.ProjectName.setGeometry(QRect(50, 10, 81, 41))
        font = QFont()
        font.setPointSize(16)
        self.ProjectName.setFont(font)
        self.tentlogo2 = QLabel(self.frame)
        self.tentlogo2.setObjectName(u"tentlogo2")
        self.tentlogo2.setGeometry(QRect(10, 10, 40, 40))
        self.tentlogo2.setMaximumSize(QSize(40, 40))
        self.tentlogo2.setPixmap(QPixmap(u":/icons/webcam-2-256.png"))
        self.tentlogo2.setScaledContents(True)
        self.Home_button = QPushButton(self.frame)
        self.Home_button.setObjectName(u"Home_button")
        self.Home_button.setGeometry(QRect(10, 60, 121, 28))
        font1 = QFont()
        font1.setPointSize(11)
        self.Home_button.setFont(font1)
        icon = QIcon()
        icon.addFile(u":/icons/home-4-256.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon.addFile(u":/icons/home-4-256-W.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.Home_button.setIcon(icon)
        self.Home_button.setIconSize(QSize(14, 14))
        self.Home_button.setCheckable(True)
        self.Home_button.setAutoExclusive(True)
        self.Import_button = QPushButton(self.frame)
        self.Import_button.setObjectName(u"Import_button")
        self.Import_button.setGeometry(QRect(10, 90, 121, 28))
        self.Import_button.setFont(font1)
        icon1 = QIcon()
        icon1.addFile(u":/icons/low-importance-256.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon1.addFile(u":/icons/low-importance-256-W.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.Import_button.setIcon(icon1)
        self.Import_button.setIconSize(QSize(14, 14))
        self.Import_button.setCheckable(True)
        self.Import_button.setAutoRepeat(False)
        self.Import_button.setAutoExclusive(True)
        self.Analytics_button = QPushButton(self.frame)
        self.Analytics_button.setObjectName(u"Analytics_button")
        self.Analytics_button.setGeometry(QRect(10, 120, 121, 28))
        self.Analytics_button.setFont(font1)
        icon2 = QIcon()
        icon2.addFile(u":/icons/analytics-256.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon2.addFile(u":/icons/analytics-256-W.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.Analytics_button.setIcon(icon2)
        self.Analytics_button.setIconSize(QSize(14, 14))
        self.Analytics_button.setCheckable(True)
        self.Analytics_button.setAutoExclusive(True)
        self.pushButton_10 = QPushButton(self.frame)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(10, 590, 121, 31))
        self.pushButton_10.setFont(font1)
        icon3 = QIcon()
        icon3.addFile(u":/icons/close-window-256.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon3.addFile(u":/icons/close-window-256-W.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.pushButton_10.setIcon(icon3)
        self.pushButton_10.setIconSize(QSize(14, 14))
        self.stackedPanels = QStackedWidget(self.centralwidget)
        self.stackedPanels.setObjectName(u"stackedPanels")
        self.stackedPanels.setGeometry(QRect(150, 10, 1156, 631))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedPanels.sizePolicy().hasHeightForWidth())
        self.stackedPanels.setSizePolicy(sizePolicy)
        self.stackedPanels.setMinimumSize(QSize(50, 0))
        self.stackedPanels.setStyleSheet(u"border-color: rgb(0, 0, 0);\n"
"")
        self.stackedPanels.setFrameShape(QFrame.Shape.WinPanel)
        self.stackedPanels.setFrameShadow(QFrame.Shadow.Raised)
        self.stackedPanels.setLineWidth(5)
        self.TutorialPage = QWidget()
        self.TutorialPage.setObjectName(u"TutorialPage")
        self.frame_10 = QFrame(self.TutorialPage)
        self.frame_10.setObjectName(u"frame_10")
        self.frame_10.setGeometry(QRect(10, 10, 181, 61))
        self.frame_10.setFrameShape(QFrame.Shape.Box)
        self.frame_10.setFrameShadow(QFrame.Shadow.Plain)
        self.tutorial_namepage = QLabel(self.frame_10)
        self.tutorial_namepage.setObjectName(u"tutorial_namepage")
        self.tutorial_namepage.setGeometry(QRect(51, 14, 131, 31))
        self.tutorial_namepage.setFont(font)
        self.logo_tutorial = QLabel(self.frame_10)
        self.logo_tutorial.setObjectName(u"logo_tutorial")
        self.logo_tutorial.setGeometry(QRect(10, 10, 41, 41))
        self.logo_tutorial.setPixmap(QPixmap(u":/icons/webcam-2-256.png"))
        self.logo_tutorial.setScaledContents(True)
        self.frame_11 = QFrame(self.TutorialPage)
        self.frame_11.setObjectName(u"frame_11")
        self.frame_11.setGeometry(QRect(10, 80, 591, 491))
        self.frame_11.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QFrame.Shadow.Raised)
        self.label_2 = QLabel(self.frame_11)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 10, 91, 41))
        font2 = QFont()
        font2.setPointSize(20)
        self.label_2.setFont(font2)
        self.stepbystepTutorial_text = QTextEdit(self.frame_11)
        self.stepbystepTutorial_text.setObjectName(u"stepbystepTutorial_text")
        self.stepbystepTutorial_text.setGeometry(QRect(10, 50, 571, 431))
        self.frame_12 = QFrame(self.TutorialPage)
        self.frame_12.setObjectName(u"frame_12")
        self.frame_12.setGeometry(QRect(603, 80, 541, 491))
        self.frame_12.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_12.setFrameShadow(QFrame.Shadow.Raised)
        self.label_3 = QLabel(self.frame_12)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 10, 171, 41))
        self.label_3.setFont(font2)
        self.center_video_preview_label_2 = QLabel(self.frame_12)
        self.center_video_preview_label_2.setObjectName(u"center_video_preview_label_2")
        self.center_video_preview_label_2.setGeometry(QRect(10, 60, 521, 351))
        font3 = QFont()
        font3.setPointSize(18)
        font3.setItalic(True)
        self.center_video_preview_label_2.setFont(font3)
        self.center_video_preview_label_2.setFrameShape(QFrame.Shape.WinPanel)
        self.center_video_preview_label_2.setFrameShadow(QFrame.Shadow.Raised)
        self.center_video_preview_label_2.setLineWidth(2)
        self.center_video_preview_label_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.pushButton_5 = QPushButton(self.TutorialPage)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(960, 510, 181, 51))
        self.pushButton_5.setFont(font)
        self.stackedPanels.addWidget(self.TutorialPage)
        self.Homepage = QWidget()
        self.Homepage.setObjectName(u"Homepage")
        self.frame_5 = QFrame(self.Homepage)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(10, -1, 311, 91))
        self.frame_5.setFrameShape(QFrame.Shape.Box)
        self.frame_5.setFrameShadow(QFrame.Shadow.Plain)
        self.Homepage_label = QLabel(self.frame_5)
        self.Homepage_label.setObjectName(u"Homepage_label")
        self.Homepage_label.setGeometry(QRect(110, 10, 181, 51))
        font4 = QFont()
        font4.setPointSize(22)
        self.Homepage_label.setFont(font4)
        self.label_14 = QLabel(self.frame_5)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(20, 10, 71, 61))
        self.label_14.setPixmap(QPixmap(u":/icons/webcam-2-256.png"))
        self.label_14.setScaledContents(True)
        self.slogan1 = QLabel(self.Homepage)
        self.slogan1.setObjectName(u"slogan1")
        self.slogan1.setGeometry(QRect(20, 110, 471, 41))
        font5 = QFont()
        font5.setFamilies([u"Mongolian Baiti"])
        font5.setPointSize(16)
        font5.setStyleStrategy(QFont.PreferDefault)
        self.slogan1.setFont(font5)
        self.slogan1.setTextFormat(Qt.TextFormat.PlainText)
        self.slogan1.setMargin(0)
        self.slogan2 = QLabel(self.Homepage)
        self.slogan2.setObjectName(u"slogan2")
        self.slogan2.setGeometry(QRect(20, 150, 371, 41))
        font6 = QFont()
        font6.setFamilies([u"Georgia"])
        font6.setPointSize(24)
        self.slogan2.setFont(font6)
        self.slogan3 = QLabel(self.Homepage)
        self.slogan3.setObjectName(u"slogan3")
        self.slogan3.setGeometry(QRect(20, 200, 361, 41))
        self.slogan3.setFont(font6)
        self.ImageDesign_Placeholder1 = QFrame(self.Homepage)
        self.ImageDesign_Placeholder1.setObjectName(u"ImageDesign_Placeholder1")
        self.ImageDesign_Placeholder1.setGeometry(QRect(470, 10, 205, 490))
        self.ImageDesign_Placeholder1.setFrameShape(QFrame.Shape.StyledPanel)
        self.ImageDesign_Placeholder1.setFrameShadow(QFrame.Shadow.Raised)
        self.ImageDesign_Placeholder2 = QFrame(self.Homepage)
        self.ImageDesign_Placeholder2.setObjectName(u"ImageDesign_Placeholder2")
        self.ImageDesign_Placeholder2.setGeometry(QRect(700, 80, 205, 490))
        self.ImageDesign_Placeholder2.setFrameShape(QFrame.Shape.StyledPanel)
        self.ImageDesign_Placeholder2.setFrameShadow(QFrame.Shadow.Raised)
        self.ImageDesign_Placeholder1_2 = QFrame(self.Homepage)
        self.ImageDesign_Placeholder1_2.setObjectName(u"ImageDesign_Placeholder1_2")
        self.ImageDesign_Placeholder1_2.setGeometry(QRect(930, 10, 205, 490))
        self.ImageDesign_Placeholder1_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.ImageDesign_Placeholder1_2.setFrameShadow(QFrame.Shadow.Raised)
        self.small_intro = QLabel(self.Homepage)
        self.small_intro.setObjectName(u"small_intro")
        self.small_intro.setGeometry(QRect(20, 230, 421, 151))
        self.small_intro.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.small_intro.setTextFormat(Qt.TextFormat.PlainText)
        self.small_intro.setAlignment(Qt.AlignmentFlag.AlignJustify|Qt.AlignmentFlag.AlignVCenter)
        self.small_intro.setWordWrap(False)
        self.label_22 = QLabel(self.Homepage)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(20, 380, 161, 16))
        font7 = QFont()
        font7.setFamilies([u"Mongolian Baiti"])
        font7.setPointSize(14)
        self.label_22.setFont(font7)
        self.SessionName_textEdit = QTextEdit(self.Homepage)
        self.SessionName_textEdit.setObjectName(u"SessionName_textEdit")
        self.SessionName_textEdit.setGeometry(QRect(20, 400, 401, 41))
        self.HomeToImport_button = QPushButton(self.Homepage)
        self.HomeToImport_button.setObjectName(u"HomeToImport_button")
        self.HomeToImport_button.setGeometry(QRect(120, 450, 191, 31))
        font8 = QFont()
        font8.setFamilies([u"Mongolian Baiti"])
        font8.setPointSize(16)
        self.HomeToImport_button.setFont(font8)
        self.HomeToTutorial_button = QPushButton(self.Homepage)
        self.HomeToTutorial_button.setObjectName(u"HomeToTutorial_button")
        self.HomeToTutorial_button.setGeometry(QRect(20, 590, 191, 31))
        self.HomeToTutorial_button.setFont(font8)
        self.stackedPanels.addWidget(self.Homepage)
        self.DatasetPage = QWidget()
        self.DatasetPage.setObjectName(u"DatasetPage")
        self.frame_2 = QFrame(self.DatasetPage)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(10, 60, 901, 411))
        self.frame_2.setFrameShape(QFrame.Shape.Box)
        self.frame_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.frame_2.setLineWidth(2)
        self.status_label = QLabel(self.frame_2)
        self.status_label.setObjectName(u"status_label")
        self.status_label.setGeometry(QRect(70, 10, 131, 21))
        palette = QPalette()
        brush = QBrush(QColor(0, 255, 0, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush1 = QBrush(QColor(0, 255, 0, 128))
        brush1.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush1)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        brush2 = QBrush(QColor(0, 255, 0, 128))
        brush2.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush2)
#endif
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        brush3 = QBrush(QColor(0, 255, 0, 128))
        brush3.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush3)
#endif
        self.status_label.setPalette(palette)
        font9 = QFont()
        font9.setFamilies([u"Segoe UI"])
        font9.setPointSize(12)
        font9.setBold(True)
        self.status_label.setFont(font9)
        self.status_label.setStyleSheet(u"color: rgb(0, 255, 0);")
        self.status_label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.label_12 = QLabel(self.frame_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(20, 10, 51, 21))
        font10 = QFont()
        font10.setFamilies([u"Segoe UI"])
        font10.setPointSize(12)
        self.label_12.setFont(font10)
        self.label_12.setAutoFillBackground(True)
        self.gridLayout_2 = QGridLayout(self.frame_2)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.camera_feed = QLabel(self.frame_2)
        self.camera_feed.setObjectName(u"camera_feed")
        self.camera_feed.setMaximumSize(QSize(450, 300))
        font11 = QFont()
        font11.setFamilies([u"Segoe UI"])
        font11.setPointSize(16)
        font11.setBold(False)
        font11.setItalic(True)
        self.camera_feed.setFont(font11)
        self.camera_feed.setFrameShape(QFrame.Shape.WinPanel)
        self.camera_feed.setFrameShadow(QFrame.Shadow.Raised)
        self.camera_feed.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout_2.addWidget(self.camera_feed, 0, 0, 1, 2)

        self.white_frame_feed = QLabel(self.frame_2)
        self.white_frame_feed.setObjectName(u"white_frame_feed")
        self.white_frame_feed.setMaximumSize(QSize(450, 300))
        self.white_frame_feed.setFont(font11)
        self.white_frame_feed.setFrameShape(QFrame.Shape.WinPanel)
        self.white_frame_feed.setFrameShadow(QFrame.Shadow.Raised)
        self.white_frame_feed.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout_2.addWidget(self.white_frame_feed, 0, 2, 1, 2)

        self.label = QLabel(self.frame_2)
        self.label.setObjectName(u"label")
        self.label.setMaximumSize(QSize(451, 31))
        font12 = QFont()
        font12.setFamilies([u"Segoe UI"])
        font12.setPointSize(16)
        self.label.setFont(font12)
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 2)

        self.label_4 = QLabel(self.frame_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setMaximumSize(QSize(451, 31))
        self.label_4.setFont(font12)
        self.label_4.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout_2.addWidget(self.label_4, 1, 2, 1, 2)

        self.showCameraLandmarksChkBox = QCheckBox(self.frame_2)
        self.showCameraLandmarksChkBox.setObjectName(u"showCameraLandmarksChkBox")
        self.showCameraLandmarksChkBox.setMaximumSize(QSize(221, 31))
        font13 = QFont()
        font13.setFamilies([u"Segoe UI"])
        font13.setPointSize(14)
        self.showCameraLandmarksChkBox.setFont(font13)
        self.showCameraLandmarksChkBox.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))

        self.gridLayout_2.addWidget(self.showCameraLandmarksChkBox, 2, 0, 1, 2)

        self.show_whiteframe_boundingbox = QCheckBox(self.frame_2)
        self.show_whiteframe_boundingbox.setObjectName(u"show_whiteframe_boundingbox")
        self.show_whiteframe_boundingbox.setMaximumSize(QSize(221, 31))
        self.show_whiteframe_boundingbox.setFont(font13)
        self.show_whiteframe_boundingbox.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))

        self.gridLayout_2.addWidget(self.show_whiteframe_boundingbox, 2, 2, 1, 2)

        self.showCameraBoundingBoxChkBox = QCheckBox(self.frame_2)
        self.showCameraBoundingBoxChkBox.setObjectName(u"showCameraBoundingBoxChkBox")
        self.showCameraBoundingBoxChkBox.setMaximumSize(QSize(221, 31))
        self.showCameraBoundingBoxChkBox.setFont(font13)
        self.showCameraBoundingBoxChkBox.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))

        self.gridLayout_2.addWidget(self.showCameraBoundingBoxChkBox, 3, 0, 1, 1)

        self.show_skeleton_camera = QCheckBox(self.frame_2)
        self.show_skeleton_camera.setObjectName(u"show_skeleton_camera")
        self.show_skeleton_camera.setMaximumSize(QSize(221, 31))
        self.show_skeleton_camera.setFont(font13)
        self.show_skeleton_camera.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))

        self.gridLayout_2.addWidget(self.show_skeleton_camera, 3, 1, 1, 1)

        self.darkMode_whiteframe = QCheckBox(self.frame_2)
        self.darkMode_whiteframe.setObjectName(u"darkMode_whiteframe")
        self.darkMode_whiteframe.setMaximumSize(QSize(221, 31))
        self.darkMode_whiteframe.setFont(font13)
        self.darkMode_whiteframe.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))

        self.gridLayout_2.addWidget(self.darkMode_whiteframe, 3, 2, 1, 1)

        self.show_skeleton_white_frame = QCheckBox(self.frame_2)
        self.show_skeleton_white_frame.setObjectName(u"show_skeleton_white_frame")
        self.show_skeleton_white_frame.setMaximumSize(QSize(221, 31))
        self.show_skeleton_white_frame.setFont(font13)
        self.show_skeleton_white_frame.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))

        self.gridLayout_2.addWidget(self.show_skeleton_white_frame, 3, 3, 1, 1)

        self.camera_feed.raise_()
        self.white_frame_feed.raise_()
        self.darkMode_whiteframe.raise_()
        self.show_whiteframe_boundingbox.raise_()
        self.showCameraLandmarksChkBox.raise_()
        self.showCameraBoundingBoxChkBox.raise_()
        self.label.raise_()
        self.label_4.raise_()
        self.show_skeleton_camera.raise_()
        self.show_skeleton_white_frame.raise_()
        self.label_12.raise_()
        self.status_label.raise_()
        self.frame_4 = QFrame(self.DatasetPage)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(10, 480, 901, 101))
        self.frame_4.setFrameShape(QFrame.Shape.Box)
        self.frame_4.setFrameShadow(QFrame.Shadow.Sunken)
        self.frame_4.setLineWidth(2)
        self.gridLayout_4 = QGridLayout(self.frame_4)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.label_7 = QLabel(self.frame_4)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setMaximumSize(QSize(81, 28))
        self.label_7.setFont(font12)
        self.label_7.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_4.addWidget(self.label_7, 0, 0, 1, 1)

        self.action_comboBox = QComboBox(self.frame_4)
        self.action_comboBox.setObjectName(u"action_comboBox")
        self.action_comboBox.setFont(font13)
        self.action_comboBox.setEditable(True)

        self.gridLayout_4.addWidget(self.action_comboBox, 0, 1, 1, 2)

        self.refresh_button = QPushButton(self.frame_4)
        self.refresh_button.setObjectName(u"refresh_button")
        self.refresh_button.setFont(font13)

        self.gridLayout_4.addWidget(self.refresh_button, 0, 3, 1, 1)

        self.recording_button = QPushButton(self.frame_4)
        self.recording_button.setObjectName(u"recording_button")
        palette1 = QPalette()
        brush4 = QBrush(QColor(0, 0, 0, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush4)
        brush5 = QBrush(QColor(170, 255, 127, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush5)
        brush6 = QBrush(QColor(170, 255, 255, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Light, brush6)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush4)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush4)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush5)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush5)
        brush7 = QBrush(QColor(0, 0, 0, 128))
        brush7.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush7)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush5)
        brush8 = QBrush(QColor(255, 255, 255, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Inactive, QPalette.Light, brush8)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush5)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush5)
        brush9 = QBrush(QColor(0, 0, 0, 128))
        brush9.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush9)
#endif
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.Light, brush8)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        brush10 = QBrush(QColor(255, 255, 255, 135))
        brush10.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush10)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush5)
        brush11 = QBrush(QColor(0, 0, 0, 128))
        brush11.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush11)
#endif
        self.recording_button.setPalette(palette1)
        font14 = QFont()
        font14.setFamilies([u"Segoe UI"])
        font14.setPointSize(16)
        font14.setBold(True)
        self.recording_button.setFont(font14)
        self.recording_button.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.recording_button.setStyleSheet(u"background-color: rgb(170, 255, 127);\n"
"border-radius: 15px; /* Adjust the radius as needed */\n"
"color: black; /* Set the text color */\n"
"border: 1px solid black; /* Optional: Add a border */")

        self.gridLayout_4.addWidget(self.recording_button, 0, 4, 2, 1)

        self.add_action_button = QPushButton(self.frame_4)
        self.add_action_button.setObjectName(u"add_action_button")
        self.add_action_button.setFont(font13)

        self.gridLayout_4.addWidget(self.add_action_button, 1, 1, 1, 1)

        self.delete_action_button = QPushButton(self.frame_4)
        self.delete_action_button.setObjectName(u"delete_action_button")
        self.delete_action_button.setFont(font13)

        self.gridLayout_4.addWidget(self.delete_action_button, 1, 2, 1, 1)

        self.groupBox = QGroupBox(self.DatasetPage)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(920, 60, 221, 521))
        self.groupBox.setFont(font14)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setStyleSheet(u"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:2 rgba(255, 255, 255, 255));")
        self.groupBox.setFlat(False)
        self.gridLayout_5 = QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.label_8 = QLabel(self.groupBox)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setMaximumSize(QSize(121, 21))
        self.label_8.setFont(font10)

        self.gridLayout_5.addWidget(self.label_8, 0, 0, 1, 1)

        self.directoryLineEdit = QLineEdit(self.groupBox)
        self.directoryLineEdit.setObjectName(u"directoryLineEdit")
        self.directoryLineEdit.setMaximumSize(QSize(261, 31))
        font15 = QFont()
        font15.setFamilies([u"Segoe UI"])
        font15.setPointSize(10)
        font15.setItalic(True)
        self.directoryLineEdit.setFont(font15)

        self.gridLayout_5.addWidget(self.directoryLineEdit, 1, 0, 1, 2)

        self.browseButton = QPushButton(self.groupBox)
        self.browseButton.setObjectName(u"browseButton")
        self.browseButton.setMaximumSize(QSize(91, 31))
        font16 = QFont()
        font16.setFamilies([u"Segoe UI"])
        font16.setPointSize(11)
        self.browseButton.setFont(font16)

        self.gridLayout_5.addWidget(self.browseButton, 2, 0, 1, 1)

        self.action_table = QTableWidget(self.groupBox)
        if (self.action_table.columnCount() < 2):
            self.action_table.setColumnCount(2)
        if (self.action_table.rowCount() < 7):
            self.action_table.setRowCount(7)
        self.action_table.setObjectName(u"action_table")
        self.action_table.setMaximumSize(QSize(261, 181))
        self.action_table.setFrameShape(QFrame.Shape.WinPanel)
        self.action_table.setFrameShadow(QFrame.Shadow.Raised)
        self.action_table.setLineWidth(2)
        self.action_table.setAutoScrollMargin(9)
        self.action_table.setProperty(u"showDropIndicator", False)
        self.action_table.setDragEnabled(False)
        self.action_table.setDragDropOverwriteMode(False)
        self.action_table.setShowGrid(True)
        self.action_table.setGridStyle(Qt.PenStyle.SolidLine)
        self.action_table.setSortingEnabled(False)
        self.action_table.setWordWrap(True)
        self.action_table.setCornerButtonEnabled(False)
        self.action_table.setRowCount(7)
        self.action_table.setColumnCount(2)
        self.action_table.horizontalHeader().setCascadingSectionResizes(False)
        self.action_table.horizontalHeader().setMinimumSectionSize(37)
        self.action_table.horizontalHeader().setDefaultSectionSize(111)
        self.action_table.horizontalHeader().setProperty(u"showSortIndicator", False)
        self.action_table.verticalHeader().setVisible(False)
        self.action_table.verticalHeader().setDefaultSectionSize(25)

        self.gridLayout_5.addWidget(self.action_table, 3, 0, 1, 2)

        self.refresh_action_list = QPushButton(self.groupBox)
        self.refresh_action_list.setObjectName(u"refresh_action_list")
        self.refresh_action_list.setMaximumSize(QSize(91, 31))
        self.refresh_action_list.setFont(font1)
        self.refresh_action_list.setAutoExclusive(True)

        self.gridLayout_5.addWidget(self.refresh_action_list, 4, 0, 1, 1)

        self.label_11 = QLabel(self.groupBox)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setMaximumSize(QSize(151, 21))
        font17 = QFont()
        font17.setFamilies([u"Segoe UI"])
        font17.setPointSize(12)
        font17.setBold(False)
        self.label_11.setFont(font17)
        self.label_11.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_5.addWidget(self.label_11, 5, 0, 1, 1)

        self.interval_slider = QSlider(self.groupBox)
        self.interval_slider.setObjectName(u"interval_slider")
        self.interval_slider.setMaximumSize(QSize(211, 21))
        self.interval_slider.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.interval_slider.setMinimum(1)
        self.interval_slider.setMaximum(10)
        self.interval_slider.setSliderPosition(3)
        self.interval_slider.setOrientation(Qt.Orientation.Horizontal)
        self.interval_slider.setTickPosition(QSlider.TickPosition.TicksAbove)

        self.gridLayout_5.addWidget(self.interval_slider, 6, 0, 1, 1)

        self.interval_label = QLabel(self.groupBox)
        self.interval_label.setObjectName(u"interval_label")
        self.interval_label.setMaximumSize(QSize(41, 41))
        font18 = QFont()
        font18.setFamilies([u"Segoe UI"])
        font18.setPointSize(18)
        font18.setBold(True)
        self.interval_label.setFont(font18)
        self.interval_label.setStyleSheet(u"border-color: rgb(0, 0, 0);\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.interval_label.setFrameShape(QFrame.Shape.Box)
        self.interval_label.setFrameShadow(QFrame.Shadow.Sunken)
        self.interval_label.setLineWidth(1)
        self.interval_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.interval_label.setMargin(0)

        self.gridLayout_5.addWidget(self.interval_label, 6, 1, 1, 1)

        self.label_13 = QLabel(self.groupBox)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setMaximumSize(QSize(171, 21))
        font19 = QFont()
        font19.setPointSize(12)
        self.label_13.setFont(font19)
        self.label_13.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_5.addWidget(self.label_13, 7, 0, 1, 1)

        self.sequence_slider = QSlider(self.groupBox)
        self.sequence_slider.setObjectName(u"sequence_slider")
        self.sequence_slider.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.sequence_slider.setMinimum(1)
        self.sequence_slider.setMaximum(60)
        self.sequence_slider.setValue(30)
        self.sequence_slider.setSliderPosition(30)
        self.sequence_slider.setOrientation(Qt.Orientation.Horizontal)
        self.sequence_slider.setTickPosition(QSlider.TickPosition.TicksAbove)

        self.gridLayout_5.addWidget(self.sequence_slider, 8, 0, 1, 1)

        self.sequence_label = QLabel(self.groupBox)
        self.sequence_label.setObjectName(u"sequence_label")
        self.sequence_label.setMaximumSize(QSize(41, 41))
        self.sequence_label.setFont(font18)
        self.sequence_label.setStyleSheet(u"border-color: rgb(0, 0, 0);\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.sequence_label.setFrameShape(QFrame.Shape.Box)
        self.sequence_label.setFrameShadow(QFrame.Shadow.Sunken)
        self.sequence_label.setLineWidth(1)
        self.sequence_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.sequence_label.setMargin(0)

        self.gridLayout_5.addWidget(self.sequence_label, 8, 1, 1, 1)

        self.frame_3 = QFrame(self.DatasetPage)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(10, 10, 1131, 41))
        self.frame_3.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout_5 = QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.label_Camera = QLabel(self.frame_3)
        self.label_Camera.setObjectName(u"label_Camera")
        self.label_Camera.setFont(font13)

        self.horizontalLayout_5.addWidget(self.label_Camera)

        self.cameraComboBox = QComboBox(self.frame_3)
        self.cameraComboBox.setObjectName(u"cameraComboBox")
        self.cameraComboBox.setFont(font13)
        self.cameraComboBox.setEditable(True)

        self.horizontalLayout_5.addWidget(self.cameraComboBox)

        self.openCamera = QPushButton(self.frame_3)
        self.openCamera.setObjectName(u"openCamera")
        self.openCamera.setFont(font10)

        self.horizontalLayout_5.addWidget(self.openCamera)

        self.closeCamera = QPushButton(self.frame_3)
        self.closeCamera.setObjectName(u"closeCamera")
        self.closeCamera.setFont(font10)

        self.horizontalLayout_5.addWidget(self.closeCamera)

        self.label_10 = QLabel(self.frame_3)
        self.label_10.setObjectName(u"label_10")
        font20 = QFont()
        font20.setFamilies([u"Segoe UI"])
        font20.setPointSize(10)
        self.label_10.setFont(font20)

        self.horizontalLayout_5.addWidget(self.label_10)

        self.fps_label = QLabel(self.frame_3)
        self.fps_label.setObjectName(u"fps_label")
        palette2 = QPalette()
        brush12 = QBrush(QColor(170, 85, 255, 255))
        brush12.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush12)
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush12)
        brush13 = QBrush(QColor(120, 120, 120, 255))
        brush13.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush13)
        self.fps_label.setPalette(palette2)
        font21 = QFont()
        font21.setFamilies([u"Segoe UI"])
        font21.setPointSize(20)
        font21.setBold(True)
        self.fps_label.setFont(font21)

        self.horizontalLayout_5.addWidget(self.fps_label)

        self.label_5 = QLabel(self.frame_3)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setFont(font20)

        self.horizontalLayout_5.addWidget(self.label_5)

        self.cpu_label = QLabel(self.frame_3)
        self.cpu_label.setObjectName(u"cpu_label")
        palette3 = QPalette()
        brush14 = QBrush(QColor(0, 85, 255, 255))
        brush14.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush14)
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush14)
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush13)
        self.cpu_label.setPalette(palette3)
        self.cpu_label.setFont(font21)

        self.horizontalLayout_5.addWidget(self.cpu_label)

        self.label_6 = QLabel(self.frame_3)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setFont(font20)

        self.horizontalLayout_5.addWidget(self.label_6)

        self.ram_label = QLabel(self.frame_3)
        self.ram_label.setObjectName(u"ram_label")
        palette4 = QPalette()
        brush15 = QBrush(QColor(170, 0, 0, 255))
        brush15.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush15)
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush15)
        palette4.setBrush(QPalette.Disabled, QPalette.WindowText, brush13)
        self.ram_label.setPalette(palette4)
        self.ram_label.setFont(font21)

        self.horizontalLayout_5.addWidget(self.ram_label)

        self.label_9 = QLabel(self.frame_3)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setFont(font20)

        self.horizontalLayout_5.addWidget(self.label_9)

        self.gpu_label = QLabel(self.frame_3)
        self.gpu_label.setObjectName(u"gpu_label")
        palette5 = QPalette()
        brush16 = QBrush(QColor(85, 170, 0, 255))
        brush16.setStyle(Qt.SolidPattern)
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush16)
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush16)
        palette5.setBrush(QPalette.Disabled, QPalette.WindowText, brush13)
        self.gpu_label.setPalette(palette5)
        self.gpu_label.setFont(font21)

        self.horizontalLayout_5.addWidget(self.gpu_label)

        self.stackedPanels.addWidget(self.DatasetPage)
        self.frame_4.raise_()
        self.frame_2.raise_()
        self.groupBox.raise_()
        self.frame_3.raise_()
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.session_frame = QFrame(self.page_4)
        self.session_frame.setObjectName(u"session_frame")
        self.session_frame.setGeometry(QRect(0, -6, 1151, 52))
        self.session_frame.setFrameShape(QFrame.Shape.NoFrame)
        self.session_frame.setFrameShadow(QFrame.Shadow.Plain)
        self.horizontalLayout_7 = QHBoxLayout(self.session_frame)
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.date_label_3 = QLabel(self.session_frame)
        self.date_label_3.setObjectName(u"date_label_3")
        self.date_label_3.setFont(font20)

        self.horizontalLayout_7.addWidget(self.date_label_3)

        self.date_label_4 = QLabel(self.session_frame)
        self.date_label_4.setObjectName(u"date_label_4")
        self.date_label_4.setMaximumSize(QSize(61, 20))
        self.date_label_4.setFont(font20)

        self.horizontalLayout_7.addWidget(self.date_label_4)

        self.day_label_2 = QLabel(self.session_frame)
        self.day_label_2.setObjectName(u"day_label_2")
        font22 = QFont()
        font22.setFamilies([u"Segoe UI"])
        font22.setPointSize(18)
        font22.setItalic(False)
        self.day_label_2.setFont(font22)

        self.horizontalLayout_7.addWidget(self.day_label_2)

        self.label_19 = QLabel(self.session_frame)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setMaximumSize(QSize(31, 21))
        self.label_19.setFont(font20)

        self.horizontalLayout_7.addWidget(self.label_19)

        self.timeLCD_2 = QLCDNumber(self.session_frame)
        self.timeLCD_2.setObjectName(u"timeLCD_2")
        self.timeLCD_2.setMaximumSize(QSize(161, 41))
        font23 = QFont()
        font23.setPointSize(10)
        self.timeLCD_2.setFont(font23)
        self.timeLCD_2.setAutoFillBackground(True)
        self.timeLCD_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.timeLCD_2.setLineWidth(1)
        self.timeLCD_2.setMidLineWidth(0)
        self.timeLCD_2.setDigitCount(8)
        self.timeLCD_2.setSegmentStyle(QLCDNumber.SegmentStyle.Filled)

        self.horizontalLayout_7.addWidget(self.timeLCD_2)

        self.label_40 = QLabel(self.page_4)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(720, 33, 411, 41))
        self.label_40.setFont(font13)
        self.label_40.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.keypointsOnlyChkBox_Center_analytics = QCheckBox(self.page_4)
        self.keypointsOnlyChkBox_Center_analytics.setObjectName(u"keypointsOnlyChkBox_Center_analytics")
        self.keypointsOnlyChkBox_Center_analytics.setGeometry(QRect(970, 70, 141, 31))
        self.keypointsOnlyChkBox_Center_analytics.setAutoFillBackground(False)
        self.center_video_preview_label = QLabel(self.page_4)
        self.center_video_preview_label.setObjectName(u"center_video_preview_label")
        self.center_video_preview_label.setGeometry(QRect(650, 70, 490, 240))
        self.center_video_preview_label.setFont(font3)
        self.center_video_preview_label.setFrameShape(QFrame.Shape.WinPanel)
        self.center_video_preview_label.setFrameShadow(QFrame.Shadow.Raised)
        self.center_video_preview_label.setLineWidth(2)
        self.center_video_preview_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.originalVideoOnlyChkBox_front_analytics = QCheckBox(self.page_4)
        self.originalVideoOnlyChkBox_front_analytics.setObjectName(u"originalVideoOnlyChkBox_front_analytics")
        self.originalVideoOnlyChkBox_front_analytics.setGeometry(QRect(832, 323, 131, 31))
        self.originalVideoOnlyChkBox_front_analytics.setAutoFillBackground(False)
        self.originalVideoOnlyChkBox_front_analytics.setChecked(False)
        self.front_video_preview_label = QLabel(self.page_4)
        self.front_video_preview_label.setObjectName(u"front_video_preview_label")
        self.front_video_preview_label.setGeometry(QRect(650, 313, 490, 240))
        self.front_video_preview_label.setFont(font3)
        self.front_video_preview_label.setFrameShape(QFrame.Shape.WinPanel)
        self.front_video_preview_label.setFrameShadow(QFrame.Shadow.Raised)
        self.front_video_preview_label.setLineWidth(2)
        self.front_video_preview_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.keypointsOnlyChkBox_front_analytics = QCheckBox(self.page_4)
        self.keypointsOnlyChkBox_front_analytics.setObjectName(u"keypointsOnlyChkBox_front_analytics")
        self.keypointsOnlyChkBox_front_analytics.setGeometry(QRect(970, 323, 141, 31))
        self.keypointsOnlyChkBox_front_analytics.setAutoFillBackground(False)
        self.originalVideoOnlyChkBox_center_analytics = QCheckBox(self.page_4)
        self.originalVideoOnlyChkBox_center_analytics.setObjectName(u"originalVideoOnlyChkBox_center_analytics")
        self.originalVideoOnlyChkBox_center_analytics.setGeometry(QRect(839, 70, 131, 31))
        self.originalVideoOnlyChkBox_center_analytics.setAutoFillBackground(False)
        self.originalVideoOnlyChkBox_center_analytics.setChecked(False)
        self.CenterPlacement_label = QLabel(self.page_4)
        self.CenterPlacement_label.setObjectName(u"CenterPlacement_label")
        self.CenterPlacement_label.setGeometry(QRect(650, 70, 191, 31))
        font24 = QFont()
        font24.setPointSize(12)
        font24.setItalic(True)
        self.CenterPlacement_label.setFont(font24)
        self.CenterPlacement_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.FrontPlacement_label = QLabel(self.page_4)
        self.FrontPlacement_label.setObjectName(u"FrontPlacement_label")
        self.FrontPlacement_label.setGeometry(QRect(650, 323, 191, 30))
        self.FrontPlacement_label.setFont(font24)
        self.FrontPlacement_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.visualization_stackedwidget = QStackedWidget(self.page_4)
        self.visualization_stackedwidget.setObjectName(u"visualization_stackedwidget")
        self.visualization_stackedwidget.setGeometry(QRect(0, 70, 641, 371))
        self.visualization_stackedwidget.setFrameShape(QFrame.Shape.WinPanel)
        self.visualization_stackedwidget.setLineWidth(1)
        self.Heatmap = QWidget()
        self.Heatmap.setObjectName(u"Heatmap")
        self.frame_9 = QFrame(self.Heatmap)
        self.frame_9.setObjectName(u"frame_9")
        self.frame_9.setGeometry(QRect(10, 20, 621, 54))
        self.frame_9.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout_8 = QHBoxLayout(self.frame_9)
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.label_21 = QLabel(self.frame_9)
        self.label_21.setObjectName(u"label_21")
        font25 = QFont()
        font25.setFamilies([u"Segoe UI"])
        font25.setPointSize(18)
        self.label_21.setFont(font25)
        self.label_21.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.horizontalLayout_8.addWidget(self.label_21)

        self.comboBox = QComboBox(self.frame_9)
        self.comboBox.setObjectName(u"comboBox")
        font26 = QFont()
        font26.setPointSize(14)
        self.comboBox.setFont(font26)

        self.horizontalLayout_8.addWidget(self.comboBox)

        self.pushButton = QPushButton(self.frame_9)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setMaximumSize(QSize(141, 31))
        self.pushButton.setFont(font19)

        self.horizontalLayout_8.addWidget(self.pushButton)

        self.heatmap_present_label = QLabel(self.Heatmap)
        self.heatmap_present_label.setObjectName(u"heatmap_present_label")
        self.heatmap_present_label.setGeometry(QRect(10, 90, 600, 300))
        font27 = QFont()
        font27.setPointSize(16)
        font27.setItalic(True)
        self.heatmap_present_label.setFont(font27)
        self.heatmap_present_label.setFrameShape(QFrame.Shape.WinPanel)
        self.heatmap_present_label.setFrameShadow(QFrame.Shadow.Raised)
        self.heatmap_present_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.visualization_stackedwidget.addWidget(self.Heatmap)
        self.Visualization1 = QWidget()
        self.Visualization1.setObjectName(u"Visualization1")
        self.visualization1_label = QLabel(self.Visualization1)
        self.visualization1_label.setObjectName(u"visualization1_label")
        self.visualization1_label.setGeometry(QRect(20, 29, 600, 361))
        self.visualization1_label.setFont(font27)
        self.visualization1_label.setFrameShape(QFrame.Shape.WinPanel)
        self.visualization1_label.setFrameShadow(QFrame.Shadow.Raised)
        self.visualization1_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.visualization_stackedwidget.addWidget(self.Visualization1)
        self.Visualization2 = QWidget()
        self.Visualization2.setObjectName(u"Visualization2")
        self.visualization2_label = QLabel(self.Visualization2)
        self.visualization2_label.setObjectName(u"visualization2_label")
        self.visualization2_label.setGeometry(QRect(20, 30, 600, 290))
        self.visualization2_label.setFont(font27)
        self.visualization2_label.setFrameShape(QFrame.Shape.WinPanel)
        self.visualization2_label.setFrameShadow(QFrame.Shadow.Raised)
        self.visualization2_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.visualization_stackedwidget.addWidget(self.Visualization2)
        self.pushButton_2 = QPushButton(self.page_4)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(30, 480, 150, 50))
        self.pushButton_2.setFont(font)
        self.pushButton_3 = QPushButton(self.page_4)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(240, 480, 150, 50))
        self.pushButton_3.setFont(font)
        self.pushButton_4 = QPushButton(self.page_4)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(450, 480, 150, 50))
        self.pushButton_4.setFont(font)
        self.stackedPanels.addWidget(self.page_4)
        self.session_frame.raise_()
        self.label_40.raise_()
        self.center_video_preview_label.raise_()
        self.originalVideoOnlyChkBox_center_analytics.raise_()
        self.CenterPlacement_label.raise_()
        self.visualization_stackedwidget.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.keypointsOnlyChkBox_Center_analytics.raise_()
        self.front_video_preview_label.raise_()
        self.FrontPlacement_label.raise_()
        self.originalVideoOnlyChkBox_front_analytics.raise_()
        self.keypointsOnlyChkBox_front_analytics.raise_()
        self.ImportPage = QWidget()
        self.ImportPage.setObjectName(u"ImportPage")
        self.frame_6 = QFrame(self.ImportPage)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setGeometry(QRect(10, 52, 951, 320))
        self.frame_6.setFrameShape(QFrame.Shape.NoFrame)
        self.frame_6.setFrameShadow(QFrame.Shadow.Raised)
        self.groupBox_2 = QGroupBox(self.ImportPage)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(887, 78, 251, 531))
        self.groupBox_2.setFont(font19)
        self.verticalLayout = QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.recording_window_button = QPushButton(self.groupBox_2)
        self.recording_window_button.setObjectName(u"recording_window_button")
        font28 = QFont()
        font28.setPointSize(18)
        font28.setBold(False)
        self.recording_window_button.setFont(font28)

        self.verticalLayout.addWidget(self.recording_window_button)

        self.play_pause_button_video_preview = QPushButton(self.groupBox_2)
        self.play_pause_button_video_preview.setObjectName(u"play_pause_button_video_preview")
        self.play_pause_button_video_preview.setEnabled(False)
        font29 = QFont()
        font29.setPointSize(18)
        self.play_pause_button_video_preview.setFont(font29)

        self.verticalLayout.addWidget(self.play_pause_button_video_preview)

        self.frame_7 = QFrame(self.groupBox_2)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setFrameShape(QFrame.Shape.Box)
        self.frame_7.setFrameShadow(QFrame.Shadow.Sunken)
        self.frame_7.setLineWidth(1)
        self.label_16 = QLabel(self.frame_7)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(0, 0, 231, 61))
        font30 = QFont()
        font30.setPointSize(14)
        font30.setBold(True)
        self.label_16.setFont(font30)
        self.label_16.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.behavior_change_freq_chkbox = QCheckBox(self.frame_7)
        self.behavior_change_freq_chkbox.setObjectName(u"behavior_change_freq_chkbox")
        self.behavior_change_freq_chkbox.setGeometry(QRect(10, 100, 221, 31))
        self.behavior_change_freq_chkbox.setFont(font23)
        self.tesk_taking_time_chkbox = QCheckBox(self.frame_7)
        self.tesk_taking_time_chkbox.setObjectName(u"tesk_taking_time_chkbox")
        self.tesk_taking_time_chkbox.setGeometry(QRect(10, 70, 211, 21))
        self.tesk_taking_time_chkbox.setFont(font23)
        self.behavior_count_freq_chkbox = QCheckBox(self.frame_7)
        self.behavior_count_freq_chkbox.setObjectName(u"behavior_count_freq_chkbox")
        self.behavior_count_freq_chkbox.setGeometry(QRect(10, 130, 211, 41))
        self.behavior_count_freq_chkbox.setFont(font23)
        self.label_20 = QLabel(self.frame_7)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(0, 170, 231, 61))
        self.label_20.setFont(font30)
        self.label_20.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.behavior_count_link_list_chkbox = QCheckBox(self.frame_7)
        self.behavior_count_link_list_chkbox.setObjectName(u"behavior_count_link_list_chkbox")
        self.behavior_count_link_list_chkbox.setGeometry(QRect(10, 230, 181, 51))
        self.behavior_count_link_list_chkbox.setFont(font23)
        self.event_timeline_chkbox = QCheckBox(self.frame_7)
        self.event_timeline_chkbox.setObjectName(u"event_timeline_chkbox")
        self.event_timeline_chkbox.setGeometry(QRect(10, 280, 131, 31))
        self.event_timeline_chkbox.setFont(font23)

        self.verticalLayout.addWidget(self.frame_7)

        self.analyze_video_button = QPushButton(self.groupBox_2)
        self.analyze_video_button.setObjectName(u"analyze_video_button")
        self.analyze_video_button.setEnabled(False)
        font31 = QFont()
        font31.setPointSize(16)
        font31.setBold(False)
        self.analyze_video_button.setFont(font31)

        self.verticalLayout.addWidget(self.analyze_video_button)

        self.frame_8 = QFrame(self.ImportPage)
        self.frame_8.setObjectName(u"frame_8")
        self.frame_8.setGeometry(QRect(7, 354, 431, 261))
        self.frame_8.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QFrame.Shadow.Raised)
        self.status_label_front = QLabel(self.frame_8)
        self.status_label_front.setObjectName(u"status_label_front")
        self.status_label_front.setGeometry(QRect(10, 110, 391, 21))
        font32 = QFont()
        font32.setPointSize(11)
        font32.setItalic(True)
        self.status_label_front.setFont(font32)
        self.status_label_front.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.gridLayout_6 = QGridLayout(self.frame_8)
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.import_video_button_front = QPushButton(self.frame_8)
        self.import_video_button_front.setObjectName(u"import_video_button_front")
        self.import_video_button_front.setMaximumSize(QSize(140, 50))
        self.import_video_button_front.setFont(font31)
        self.import_video_button_front.setAutoFillBackground(False)

        self.gridLayout_6.addWidget(self.import_video_button_front, 6, 2, 1, 1)

        self.front_frame_count = QLabel(self.frame_8)
        self.front_frame_count.setObjectName(u"front_frame_count")
        font33 = QFont()
        font33.setPointSize(12)
        font33.setBold(True)
        font33.setItalic(False)
        self.front_frame_count.setFont(font33)
        self.front_frame_count.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_6.addWidget(self.front_frame_count, 4, 1, 1, 1)

        self.label_15 = QLabel(self.frame_8)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setMaximumSize(QSize(211, 21))
        self.label_15.setFont(font24)

        self.gridLayout_6.addWidget(self.label_15, 0, 0, 1, 1)

        self.somelabelforprogrss_3 = QLabel(self.frame_8)
        self.somelabelforprogrss_3.setObjectName(u"somelabelforprogrss_3")
        font34 = QFont()
        font34.setPointSize(12)
        font34.setBold(False)
        font34.setItalic(True)
        self.somelabelforprogrss_3.setFont(font34)
        self.somelabelforprogrss_3.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_6.addWidget(self.somelabelforprogrss_3, 4, 0, 1, 1)

        self.somelabelforprogrss_4 = QLabel(self.frame_8)
        self.somelabelforprogrss_4.setObjectName(u"somelabelforprogrss_4")
        self.somelabelforprogrss_4.setFont(font34)
        self.somelabelforprogrss_4.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_6.addWidget(self.somelabelforprogrss_4, 5, 0, 1, 1)

        self.somelabelforprogrss = QLabel(self.frame_8)
        self.somelabelforprogrss.setObjectName(u"somelabelforprogrss")
        self.somelabelforprogrss.setFont(font34)
        self.somelabelforprogrss.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_6.addWidget(self.somelabelforprogrss, 2, 0, 1, 1)

        self.videoDirectory_front = QLineEdit(self.frame_8)
        self.videoDirectory_front.setObjectName(u"videoDirectory_front")
        self.videoDirectory_front.setMaximumSize(QSize(420, 40))
        self.videoDirectory_front.setFont(font24)
        self.videoDirectory_front.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.videoDirectory_front.setReadOnly(True)
        self.videoDirectory_front.setClearButtonEnabled(False)

        self.gridLayout_6.addWidget(self.videoDirectory_front, 1, 0, 1, 3)

        self.front_video_length = QLabel(self.frame_8)
        self.front_video_length.setObjectName(u"front_video_length")
        self.front_video_length.setFont(font33)
        self.front_video_length.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_6.addWidget(self.front_video_length, 5, 1, 1, 1)

        self.importProgressBar_front = QProgressBar(self.frame_8)
        self.importProgressBar_front.setObjectName(u"importProgressBar_front")
        self.importProgressBar_front.setMaximumSize(QSize(420, 40))
        self.importProgressBar_front.setFont(font19)
        self.importProgressBar_front.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.importProgressBar_front.setAutoFillBackground(False)
        self.importProgressBar_front.setValue(0)
        self.importProgressBar_front.setAlignment(Qt.AlignmentFlag.AlignBottom|Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing)
        self.importProgressBar_front.setInvertedAppearance(False)

        self.gridLayout_6.addWidget(self.importProgressBar_front, 3, 0, 1, 3)

        self.frame_13 = QFrame(self.ImportPage)
        self.frame_13.setObjectName(u"frame_13")
        self.frame_13.setGeometry(QRect(440, 353, 431, 261))
        self.frame_13.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_13.setFrameShadow(QFrame.Shadow.Raised)
        self.status_label_center = QLabel(self.frame_13)
        self.status_label_center.setObjectName(u"status_label_center")
        self.status_label_center.setGeometry(QRect(10, 110, 411, 21))
        self.status_label_center.setFont(font32)
        self.status_label_center.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.gridLayout_7 = QGridLayout(self.frame_13)
        self.gridLayout_7.setObjectName(u"gridLayout_7")
        self.label_17 = QLabel(self.frame_13)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setMaximumSize(QSize(211, 21))
        self.label_17.setFont(font24)

        self.gridLayout_7.addWidget(self.label_17, 0, 0, 1, 1)

        self.videoDirectory_center = QLineEdit(self.frame_13)
        self.videoDirectory_center.setObjectName(u"videoDirectory_center")
        self.videoDirectory_center.setMaximumSize(QSize(411, 27))
        self.videoDirectory_center.setFont(font24)
        self.videoDirectory_center.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.videoDirectory_center.setReadOnly(True)
        self.videoDirectory_center.setClearButtonEnabled(False)

        self.gridLayout_7.addWidget(self.videoDirectory_center, 1, 0, 1, 3)

        self.somelabelforprogrss_2 = QLabel(self.frame_13)
        self.somelabelforprogrss_2.setObjectName(u"somelabelforprogrss_2")
        self.somelabelforprogrss_2.setMaximumSize(QSize(451, 31))
        self.somelabelforprogrss_2.setFont(font34)
        self.somelabelforprogrss_2.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_7.addWidget(self.somelabelforprogrss_2, 2, 0, 1, 1)

        self.importProgressBar_center = QProgressBar(self.frame_13)
        self.importProgressBar_center.setObjectName(u"importProgressBar_center")
        self.importProgressBar_center.setMaximumSize(QSize(411, 29))
        self.importProgressBar_center.setFont(font19)
        self.importProgressBar_center.setAutoFillBackground(False)
        self.importProgressBar_center.setValue(0)
        self.importProgressBar_center.setAlignment(Qt.AlignmentFlag.AlignBottom|Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing)
        self.importProgressBar_center.setInvertedAppearance(False)

        self.gridLayout_7.addWidget(self.importProgressBar_center, 3, 0, 1, 3)

        self.somelabelforprogrss_7 = QLabel(self.frame_13)
        self.somelabelforprogrss_7.setObjectName(u"somelabelforprogrss_7")
        self.somelabelforprogrss_7.setMaximumSize(QSize(191, 31))
        self.somelabelforprogrss_7.setFont(font34)
        self.somelabelforprogrss_7.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_7.addWidget(self.somelabelforprogrss_7, 4, 0, 1, 1)

        self.center_frame_count = QLabel(self.frame_13)
        self.center_frame_count.setObjectName(u"center_frame_count")
        self.center_frame_count.setMaximumSize(QSize(71, 31))
        self.center_frame_count.setFont(font33)
        self.center_frame_count.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_7.addWidget(self.center_frame_count, 4, 1, 1, 1)

        self.somelabelforprogrss_5 = QLabel(self.frame_13)
        self.somelabelforprogrss_5.setObjectName(u"somelabelforprogrss_5")
        self.somelabelforprogrss_5.setMaximumSize(QSize(161, 31))
        self.somelabelforprogrss_5.setFont(font34)
        self.somelabelforprogrss_5.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_7.addWidget(self.somelabelforprogrss_5, 5, 0, 1, 1)

        self.center_video_length = QLabel(self.frame_13)
        self.center_video_length.setObjectName(u"center_video_length")
        self.center_video_length.setMaximumSize(QSize(71, 31))
        self.center_video_length.setFont(font33)
        self.center_video_length.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.gridLayout_7.addWidget(self.center_video_length, 5, 1, 1, 1)

        self.import_video_button_center = QPushButton(self.frame_13)
        self.import_video_button_center.setObjectName(u"import_video_button_center")
        self.import_video_button_center.setMaximumSize(QSize(110, 36))
        self.import_video_button_center.setFont(font31)
        self.import_video_button_center.setAutoFillBackground(False)

        self.gridLayout_7.addWidget(self.import_video_button_center, 6, 2, 1, 1)

        self.label_18 = QLabel(self.ImportPage)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(940, 10, 31, 17))
        self.label_18.setMaximumSize(QSize(31, 21))
        self.label_18.setFont(font20)
        self.timeLCD = QLCDNumber(self.ImportPage)
        self.timeLCD.setObjectName(u"timeLCD")
        self.timeLCD.setGeometry(QRect(980, 10, 161, 34))
        self.timeLCD.setMaximumSize(QSize(161, 41))
        self.timeLCD.setFont(font23)
        self.timeLCD.setAutoFillBackground(True)
        self.timeLCD.setFrameShadow(QFrame.Shadow.Sunken)
        self.timeLCD.setLineWidth(1)
        self.timeLCD.setMidLineWidth(0)
        self.timeLCD.setDigitCount(8)
        self.timeLCD.setSegmentStyle(QLCDNumber.SegmentStyle.Filled)
        self.video_preview_label_center = QLabel(self.ImportPage)
        self.video_preview_label_center.setObjectName(u"video_preview_label_center")
        self.video_preview_label_center.setGeometry(QRect(440, 90, 430, 260))
        self.video_preview_label_center.setMaximumSize(QSize(460, 300))
        self.video_preview_label_center.setFont(font27)
        self.video_preview_label_center.setFrameShape(QFrame.Shape.WinPanel)
        self.video_preview_label_center.setFrameShadow(QFrame.Shadow.Raised)
        self.video_preview_label_center.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.video_preview_label_front = QLabel(self.ImportPage)
        self.video_preview_label_front.setObjectName(u"video_preview_label_front")
        self.video_preview_label_front.setGeometry(QRect(7, 90, 430, 260))
        self.video_preview_label_front.setMaximumSize(QSize(460, 300))
        self.video_preview_label_front.setFont(font27)
        self.video_preview_label_front.setFrameShape(QFrame.Shape.WinPanel)
        self.video_preview_label_front.setFrameShadow(QFrame.Shadow.Raised)
        self.video_preview_label_front.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_30 = QLabel(self.ImportPage)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(20, 100, 191, 21))
        self.label_30.setMaximumSize(QSize(191, 21))
        self.label_30.setFont(font19)
        self.label_30.setAutoFillBackground(True)
        self.label_30.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_29 = QLabel(self.ImportPage)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(450, 100, 191, 21))
        self.label_29.setMaximumSize(QSize(191, 21))
        self.label_29.setFont(font19)
        self.label_29.setAutoFillBackground(True)
        self.label_29.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.day_label = QLabel(self.ImportPage)
        self.day_label.setObjectName(u"day_label")
        self.day_label.setGeometry(QRect(760, 10, 171, 31))
        self.day_label.setFont(font22)
        self.label_23 = QLabel(self.ImportPage)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(10, 10, 91, 31))
        self.label_24 = QLabel(self.ImportPage)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(710, 10, 41, 31))
        self.stackedPanels.addWidget(self.ImportPage)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1310, 33))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menuView.addAction(self.actionTutorial_Tab)
        self.menuView.addAction(self.actionAbout_Us)

        self.retranslateUi(MainWindow)

        self.stackedPanels.setCurrentIndex(1)
        self.visualization_stackedwidget.setCurrentIndex(2)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionTutorial_Tab.setText(QCoreApplication.translate("MainWindow", u"Tutorial Tab", None))
        self.actionAbout_Us.setText(QCoreApplication.translate("MainWindow", u"About Us", None))
        self.ProjectName.setText(QCoreApplication.translate("MainWindow", u"Thesis ", None))
        self.tentlogo2.setText("")
        self.Home_button.setText(QCoreApplication.translate("MainWindow", u"Home", None))
        self.Import_button.setText(QCoreApplication.translate("MainWindow", u"Import Video", None))
        self.Analytics_button.setText(QCoreApplication.translate("MainWindow", u"Analytics", None))
        self.pushButton_10.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.tutorial_namepage.setText(QCoreApplication.translate("MainWindow", u"Project Name", None))
        self.logo_tutorial.setText("")
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Tutorial", None))
        self.stepbystepTutorial_text.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt;\">Lorem ipsum odor amet, consectetuer adipiscing elit. Per nibh massa magna potenti euismod vestibulum non. Elementum eros nascetur id felis proin proin fames. Massa potenti ultrices facilisi fames hac. Eleifend amet nam habitasse elementum inceptos hac habitasse posuere platea. Sed hendrerit inceptos lacinia arcu, mattis habitasse tincidunt. Vel mauris lacinia dis lacin"
                        "ia auctor tellus integer elementum. Tempus faucibus mattis nisi consequat at habitasse. Torquent iaculis fringilla parturient dolor facilisi ad.</span></p></body></html>", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Video Tutorial", None))
        self.center_video_preview_label_2.setText(QCoreApplication.translate("MainWindow", u"Placeholder of the video or GIF tutorial", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"Back to Home", None))
        self.Homepage_label.setText(QCoreApplication.translate("MainWindow", u"Project Name", None))
        self.label_14.setText("")
        self.slogan1.setText(QCoreApplication.translate("MainWindow", u"Track.          Analyze.              Visualize", None))
        self.slogan2.setText(QCoreApplication.translate("MainWindow", u"E  v  e  r  y    A  c  t  i  o  n,", None))
        self.slogan3.setText(QCoreApplication.translate("MainWindow", u"E  v  e  r  y    D  e  t  a  i  l!", None))
        self.small_intro.setText(QCoreApplication.translate("MainWindow", u"Lorem ipsum odor amet, consectetuer adipiscing elit. \n"
"Per nibh massa magna potenti euismod vestibulum non.\n"
" Elementum eros nascetur id felis proin proin fames. \n"
"Massa potenti ultrices facilisi fames hac. \n"
"Eleifend amet nam habitasse elementum inceptos hac habitasse posuere platea. \n"
"Sed hendrerit inceptos lacinia arcu, mattis habitasse tincidunt.", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"Enter Session Name: ", None))
        self.HomeToImport_button.setText(QCoreApplication.translate("MainWindow", u"Proceed to Import", None))
        self.HomeToTutorial_button.setText(QCoreApplication.translate("MainWindow", u"Tutorial", None))
        self.status_label.setText(QCoreApplication.translate("MainWindow", u"NOT RECORDING", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Status:", None))
        self.camera_feed.setText(QCoreApplication.translate("MainWindow", u"Camera Feed will show here", None))
        self.white_frame_feed.setText(QCoreApplication.translate("MainWindow", u"Body Pose Key Points will show here", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Camera Feed", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Key Points Visualization", None))
        self.showCameraLandmarksChkBox.setText(QCoreApplication.translate("MainWindow", u"Show Body Landmarks", None))
        self.show_whiteframe_boundingbox.setText(QCoreApplication.translate("MainWindow", u"Show Bounding Boxes", None))
        self.showCameraBoundingBoxChkBox.setText(QCoreApplication.translate("MainWindow", u"Show Bounding Box", None))
        self.show_skeleton_camera.setText(QCoreApplication.translate("MainWindow", u"Show in Skeleton", None))
        self.darkMode_whiteframe.setText(QCoreApplication.translate("MainWindow", u"Dark Mode", None))
        self.show_skeleton_white_frame.setText(QCoreApplication.translate("MainWindow", u"Show in Skeleton", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"ACTION:", None))
        self.refresh_button.setText(QCoreApplication.translate("MainWindow", u"Refresh", None))
        self.recording_button.setText(QCoreApplication.translate("MainWindow", u"START\n"
"RECORDING", None))
        self.add_action_button.setText(QCoreApplication.translate("MainWindow", u"Add Action", None))
        self.delete_action_button.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Dataset Details", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Folder Location", None))
        self.browseButton.setText(QCoreApplication.translate("MainWindow", u"Browse", None))
        self.refresh_action_list.setText(QCoreApplication.translate("MainWindow", u"Refresh", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Break Interval Length", None))
        self.interval_label.setText(QCoreApplication.translate("MainWindow", u"--", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"No. of Frames per Video", None))
        self.sequence_label.setText(QCoreApplication.translate("MainWindow", u"--", None))
        self.label_Camera.setText(QCoreApplication.translate("MainWindow", u"Camera", None))
        self.openCamera.setText(QCoreApplication.translate("MainWindow", u"Open Camera", None))
        self.closeCamera.setText(QCoreApplication.translate("MainWindow", u"Close Camera", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"FPS:", None))
        self.fps_label.setText(QCoreApplication.translate("MainWindow", u"--", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"CPU Usage", None))
        self.cpu_label.setText(QCoreApplication.translate("MainWindow", u"--", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"RAM Usage", None))
        self.ram_label.setText(QCoreApplication.translate("MainWindow", u"--", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"GPU Usage", None))
        self.gpu_label.setText(QCoreApplication.translate("MainWindow", u"--", None))
        self.date_label_3.setText(QCoreApplication.translate("MainWindow", u"Session Name:", None))
        self.date_label_4.setText(QCoreApplication.translate("MainWindow", u"Today is:", None))
        self.day_label_2.setText(QCoreApplication.translate("MainWindow", u"--", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Time:", None))
        self.label_40.setText(QCoreApplication.translate("MainWindow", u"EXAMINATION FOOTAGE PLAYBACK", None))
        self.keypointsOnlyChkBox_Center_analytics.setText(QCoreApplication.translate("MainWindow", u"Keypoints Only", None))
        self.center_video_preview_label.setText(QCoreApplication.translate("MainWindow", u"Import an Examination Footage First", None))
        self.originalVideoOnlyChkBox_front_analytics.setText(QCoreApplication.translate("MainWindow", u"Original Video Only", None))
        self.front_video_preview_label.setText(QCoreApplication.translate("MainWindow", u"Import an Examination Footage First", None))
        self.keypointsOnlyChkBox_front_analytics.setText(QCoreApplication.translate("MainWindow", u"Keypoints Only", None))
        self.originalVideoOnlyChkBox_center_analytics.setText(QCoreApplication.translate("MainWindow", u"Original Video Only", None))
        self.CenterPlacement_label.setText(QCoreApplication.translate("MainWindow", u"Center Video Placement", None))
        self.FrontPlacement_label.setText(QCoreApplication.translate("MainWindow", u"Front Video Placement", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"CLASSROOM HEATMAP", None))
        self.comboBox.setCurrentText("")
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Refresh Heatmap", None))
        self.heatmap_present_label.setText(QCoreApplication.translate("MainWindow", u"Heatmap Visualization will be presented here.", None))
        self.visualization1_label.setText(QCoreApplication.translate("MainWindow", u"Visualization1 will be here", None))
        self.visualization2_label.setText(QCoreApplication.translate("MainWindow", u"Visualization2 is here", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"Heatmap ", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"Visualization 1", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"Visualization 2 ", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Analytics Options", None))
        self.recording_window_button.setText(QCoreApplication.translate("MainWindow", u"Record Session", None))
        self.play_pause_button_video_preview.setText(QCoreApplication.translate("MainWindow", u"PLAY PREVIEW", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Classroom\n"
"Heatmap View", None))
        self.behavior_change_freq_chkbox.setText(QCoreApplication.translate("MainWindow", u"Behavior Change Frequency", None))
        self.tesk_taking_time_chkbox.setText(QCoreApplication.translate("MainWindow", u"Test-Taking Time Duration", None))
        self.behavior_count_freq_chkbox.setText(QCoreApplication.translate("MainWindow", u"Behavior Count Frequency", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Other\n"
"Visualizations", None))
        self.behavior_count_link_list_chkbox.setText(QCoreApplication.translate("MainWindow", u"Behavior Count\n"
"Frequency [Linked List]", None))
        self.event_timeline_chkbox.setText(QCoreApplication.translate("MainWindow", u"Event Timeline", None))
        self.analyze_video_button.setText(QCoreApplication.translate("MainWindow", u"Analyze\n"
"Footages", None))
        self.status_label_front.setText(QCoreApplication.translate("MainWindow", u"[ IMPORT A VIDEO ]", None))
        self.import_video_button_front.setText(QCoreApplication.translate("MainWindow", u"Browse", None))
        self.front_frame_count.setText(QCoreApplication.translate("MainWindow", u"--", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Front Video File Location:", None))
        self.somelabelforprogrss_3.setText(QCoreApplication.translate("MainWindow", u"Front Video Frame Count:", None))
        self.somelabelforprogrss_4.setText(QCoreApplication.translate("MainWindow", u"Front Video Length:", None))
        self.somelabelforprogrss.setText(QCoreApplication.translate("MainWindow", u"Front Video Progress Bar", None))
        self.videoDirectory_front.setText(QCoreApplication.translate("MainWindow", u"Import a video file to be analyzed.", None))
        self.videoDirectory_front.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Find a video file", None))
        self.front_video_length.setText(QCoreApplication.translate("MainWindow", u"--", None))
        self.status_label_center.setText(QCoreApplication.translate("MainWindow", u"[ IMPORT A VIDEO ]", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Center Video File Location:", None))
        self.videoDirectory_center.setText(QCoreApplication.translate("MainWindow", u"Import a video file to be analyzed.", None))
        self.videoDirectory_center.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Find a video file", None))
        self.somelabelforprogrss_2.setText(QCoreApplication.translate("MainWindow", u"Center Video Progress Bar", None))
        self.somelabelforprogrss_7.setText(QCoreApplication.translate("MainWindow", u"Center Video Frame Count:", None))
        self.center_frame_count.setText(QCoreApplication.translate("MainWindow", u"--", None))
        self.somelabelforprogrss_5.setText(QCoreApplication.translate("MainWindow", u"Center Video Length:", None))
        self.center_video_length.setText(QCoreApplication.translate("MainWindow", u"--", None))
        self.import_video_button_center.setText(QCoreApplication.translate("MainWindow", u"Browse", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Time:", None))
        self.video_preview_label_center.setText(QCoreApplication.translate("MainWindow", u"Import a video to see preview", None))
        self.video_preview_label_front.setText(QCoreApplication.translate("MainWindow", u"Import a video to see preview", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"Video Preview [FRONT]", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"Video Preview [CENTER]", None))
        self.day_label.setText(QCoreApplication.translate("MainWindow", u"--", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"Session Name:", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"Time:", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
    # retranslateUi

